# Generated by Django 4.1.7 on 2023-03-25 23:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import stellar.stellar_backend.helpers.model_helpers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=20)),
                ('banner_color', models.CharField(max_length=7)),
                ('icon_background_color', models.CharField(max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignInData',
            fields=[
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=stellar.stellar_backend.helpers.model_helpers.generate_name, max_length=100, unique=True)),
                ('image_url', models.CharField(default='', max_length=256)),
                ('personal_color', models.CharField(default='#ffffff', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('token', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(default=stellar.stellar_backend.helpers.model_helpers.token_date)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stellar_backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stellar_backend.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('location', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=256)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stellar_backend.group')),
                ('reply_to_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_to_id', to='stellar_backend.user')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='stellar_backend.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupsMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_owner', models.BooleanField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stellar_backend.group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stellar_backend.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='group',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stellar_backend.user'),
        ),
    ]
