# Generated by Django 4.1.7 on 2023-03-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stellar_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signindata',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
