# Generated by Django 4.1.7 on 2023-03-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stellar_backend', '0003_alter_sessiontoken_token_alter_sessiontoken_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='owner_id',
            field=models.CharField(max_length=100),
        ),
    ]
