# Generated by Django 4.1.7 on 2023-03-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stellar_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='GroupsMembers',
            new_name='GroupsMember',
        ),
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
        migrations.RenameModel(
            old_name='SessionTokens',
            new_name='SessionToken',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
