# Generated by Django 4.1.7 on 2023-03-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stellar_backend', '0002_rename_groups_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signindata',
            name='email',
            field=models.EmailField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
