# Generated by Django 4.1.7 on 2023-03-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stellar_backend', '0005_alter_groupsmember_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reply_to_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
